"""Domain entities and value objects for Hexaqueue Core."""

from hexaqueue_core.domain.collateral import (
    CollateralBundle,
    CollateralKind,
    CollateralState,
    CollateralTier,
    can_transition_collateral,
)
from hexaqueue_core.domain.config import (
    CspProvider,
    ExecutionMode,
    FreeTierProfileConfig,
    HexaqueueConfig,
    HexaqueueConfigError,
    HexaqueueCoreConfig,
)
from hexaqueue_core.domain.container import (
    ContainerMount,
    ContainerRuntimeType,
    ContainerSpec,
)
from hexaqueue_core.domain.cqrs import (
    CancelJobCommand,
    CancelRunCommand,
    ClusterStatsReport,
    CreateBastionSessionCommand,
    CreatePtySessionCommand,
    ExplainJobQuery,
    GetFairShareTreeQuery,
    GetJobQuery,
    GetLogsQuery,
    GetNodesQuery,
    GetQueueStatsQuery,
    GetRunStatusQuery,
    HoldJobCommand,
    ListJobsQuery,
    RegisterCollateralCommand,
    ReleaseJobCommand,
    SettleBudgetCommand,
    StreamLogsQuery,
    SubmitRunCommand,
    SubmitSuiteCommand,
)
from hexaqueue_core.domain.dag import (
    DependencyCycleError,
    DependencySpec,
    JobDagEngine,
    TriggerCondition,
    is_dependency_blocked,
    is_dependency_satisfied,
)
from hexaqueue_core.domain.exceptions import (
    ChecksumMismatchError,
    FreeTierLimitExceededError,
    GpuAllocationError,
    HexaqueueError,
    JobStateTransitionError,
    PermissionDeniedError,
    QuotaExceededError,
    StorageVolumeError,
    SuiteCompilationError,
    VariableInterpolationError,
)
from hexaqueue_core.domain.exceptions import (
    HexaqueueConfigError as BaseHexaqueueConfigError,
)
from hexaqueue_core.domain.explainability import (
    FairShareNodeReport,
    FairShareTreeReport,
    PendingReason,
    PendingReasonCode,
    PriorityBreakdown,
    SchedulerExplainabilityEngine,
    SchedulingDecisionReport,
)
from hexaqueue_core.domain.fairshare import (
    FairShareNode,
    FairShareTree,
)
from hexaqueue_core.domain.freetier import (
    AWS_FREE_TIER_PROFILE,
    AZURE_FREE_TIER_PROFILE,
    GCP_ALWAYS_FREE_PROFILE,
    LOCAL_FREE_TIER_PROFILE,
    OCI_ALWAYS_FREE_PROFILE,
    CspFreeTierProfile,
    FreeTierBurnReport,
    FreeTierGovernor,
    get_free_tier_profile,
)
from hexaqueue_core.domain.gpu import (
    GpuAllocation,
    GpuDevice,
)
from hexaqueue_core.domain.group import (
    GroupExpansionEngine,
    JobGroupSpec,
    JobTemplateSpec,
    ResolvedJobCollection,
    ResourceOverrideSpec,
)
from hexaqueue_core.domain.job import (
    JobSpec,
)
from hexaqueue_core.domain.lifecycle import (
    JobState,
    JobStatus,
    RunOutcome,
    RunState,
    TerminalOutcome,
    can_transition_job,
    compute_run_outcome,
    compute_run_state,
)
from hexaqueue_core.domain.notification import (
    NotificationPolicy,
    NotificationTrigger,
    map_lifecycle_to_trigger,
)
from hexaqueue_core.domain.priority import (
    JobPriorityCalculator,
    PriorityWeights,
    RankedJob,
)
from hexaqueue_core.domain.redaction import (
    MultiTenantRedactionFilter,
)
from hexaqueue_core.domain.resources import (
    ResourceRequirements,
)
from hexaqueue_core.domain.run import (
    RunSpec,
)
from hexaqueue_core.domain.scheduling import (
    BatchSchedulerEngine,
    ConservativeBackfillScheduler,
    ControlledPreemptionEngine,
    PreemptionPolicy,
    ResourceSlotPool,
    SchedulingDecision,
)
from hexaqueue_core.domain.storage import (
    FilesystemType,
    SharedVolumeMount,
)
from hexaqueue_core.domain.suite import (
    ContextResolver,
    MatrixExpansionEngine,
    ResolvedContext,
    SuiteCompilationResult,
    SuiteCompiler,
    SuiteContext,
    SuiteSpec,
    TaskSpec,
    TestSpec,
)

__all__ = [
    "AWS_FREE_TIER_PROFILE",
    "AZURE_FREE_TIER_PROFILE",
    "BaseHexaqueueConfigError",
    "BatchSchedulerEngine",
    "can_transition_collateral",
    "can_transition_job",
    "CancelJobCommand",
    "CancelRunCommand",
    "ChecksumMismatchError",
    "ClusterStatsReport",
    "CollateralBundle",
    "CollateralKind",
    "CollateralState",
    "CollateralTier",
    "compute_run_outcome",
    "compute_run_state",
    "ConservativeBackfillScheduler",
    "ContainerMount",
    "ContainerRuntimeType",
    "ContainerSpec",
    "ContextResolver",
    "ControlledPreemptionEngine",
    "CreateBastionSessionCommand",
    "CreatePtySessionCommand",
    "CspFreeTierProfile",
    "CspProvider",
    "DependencyCycleError",
    "DependencySpec",
    "ExecutionMode",
    "ExplainJobQuery",
    "FairShareNode",
    "FairShareNodeReport",
    "FairShareTree",
    "FairShareTreeReport",
    "FilesystemType",
    "FreeTierBurnReport",
    "FreeTierGovernor",
    "FreeTierLimitExceededError",
    "FreeTierProfileConfig",
    "GCP_ALWAYS_FREE_PROFILE",
    "get_free_tier_profile",
    "GetFairShareTreeQuery",
    "GetJobQuery",
    "GetLogsQuery",
    "GetNodesQuery",
    "GetQueueStatsQuery",
    "GetRunStatusQuery",
    "GpuAllocation",
    "GpuAllocationError",
    "GpuDevice",
    "GroupExpansionEngine",
    "HexaqueueConfig",
    "HexaqueueConfigError",
    "HexaqueueCoreConfig",
    "HexaqueueError",
    "HoldJobCommand",
    "is_dependency_blocked",
    "is_dependency_satisfied",
    "JobDagEngine",
    "JobGroupSpec",
    "JobPriorityCalculator",
    "JobSpec",
    "JobState",
    "JobStateTransitionError",
    "JobStatus",
    "JobTemplateSpec",
    "ListJobsQuery",
    "LOCAL_FREE_TIER_PROFILE",
    "map_lifecycle_to_trigger",
    "MatrixExpansionEngine",
    "MultiTenantRedactionFilter",
    "NotificationPolicy",
    "NotificationTrigger",
    "OCI_ALWAYS_FREE_PROFILE",
    "PendingReason",
    "PendingReasonCode",
    "PermissionDeniedError",
    "PreemptionPolicy",
    "PriorityBreakdown",
    "PriorityWeights",
    "QuotaExceededError",
    "RankedJob",
    "RegisterCollateralCommand",
    "ReleaseJobCommand",
    "ResolvedContext",
    "ResolvedJobCollection",
    "ResourceOverrideSpec",
    "ResourceRequirements",
    "ResourceSlotPool",
    "RunOutcome",
    "RunSpec",
    "RunState",
    "SchedulerExplainabilityEngine",
    "SchedulingDecision",
    "SchedulingDecisionReport",
    "SettleBudgetCommand",
    "SharedVolumeMount",
    "StorageVolumeError",
    "StreamLogsQuery",
    "SubmitRunCommand",
    "SubmitSuiteCommand",
    "SuiteCompilationError",
    "SuiteCompilationResult",
    "SuiteCompiler",
    "SuiteContext",
    "SuiteSpec",
    "TaskSpec",
    "TerminalOutcome",
    "TestSpec",
    "TriggerCondition",
    "VariableInterpolationError",
]
